export const operatingLoop = [
  "Intent",
  "Spec",
  "Prototype",
  "Delegate",
  "Integrate",
  "Verify",
  "Polish",
  "Package",
];

export const cohortCadences = [
  {
    id: "ten-week",
    label: "10-week studio",
    length: "10 weeks",
    pace: "1 module/week",
    workload: "10-16 focused hours/week",
    liveSessions: "briefing + critique/review",
  },
  {
    id: "five-week",
    label: "5-week hardcore",
    length: "5 weeks",
    pace: "2 modules/week",
    workload: "18-30 focused hours/week",
    liveSessions: "production briefing + critique/review",
  },
];

export const defenseModuleNumbers = [3, 5, 8, 10];

export const modules = [
  {
    id: "module-01",
    number: 1,
    title: "Solo Studio Operating System",
    status: "complete",
    timeBudget: "6-10 hours",
    phase: "Intent",
    gate: "A clean Unity project exists with repo hygiene, agent rules, role assignments, and editor automation policy validated before production work begins.",
    summary: "Stand up an agent-safe Unity project and define the operating rules before agents touch production work.",
    templates: ["AGENT-ROLES"],
    artifacts: [
      "Unity repo with source-control hygiene",
      "AGENTS.md or CLAUDE.md Unity rules",
      "Agent role map",
      "Editor automation safety-test evidence",
    ],
  },
  {
    id: "module-02",
    number: 2,
    title: "Game Concept To Vertical Slice Spec",
    status: "complete",
    timeBudget: "8-12 hours",
    phase: "Spec",
    gate: "A fresh agent can understand the game, scope, core loop, controls, win/loss state, asset budget, and cut plan from the spec alone.",
    summary: "Convert a fuzzy game idea into a production-grade vertical-slice spec with scope and risk boundaries.",
    templates: ["GAME-THESIS", "VERTICAL-SLICE-SPEC", "CUT-PLAN"],
    artifacts: [
      "Game thesis",
      "Vertical-slice spec",
      "Cut plan",
      "Human-vs-agent delegation map",
    ],
  },
  {
    id: "module-03",
    number: 3,
    title: "Prototype Tournament",
    status: "complete",
    timeBudget: "8-14 hours",
    phase: "Prototype",
    gate: "The chosen prototype is playable in under 60 seconds from launch and proves the core loop with greybox or placeholder assets.",
    summary: "Run small playable experiments, score them, kill weak options, and choose one production loop.",
    templates: ["PLAYTEST-RUBRIC"],
    artifacts: [
      "Three to five prototype notes",
      "Prototype scoring sheet",
      "Kill memos",
      "Chosen prototype revision note",
    ],
  },
  {
    id: "module-04",
    number: 4,
    title: "Unity Architecture For Agent Teams",
    status: "complete",
    timeBudget: "8-14 hours",
    phase: "Delegate",
    gate: "A reviewer can enforce architecture boundaries before accepting agent changes.",
    summary: "Define Unity architecture, folders, scene/prefab boundaries, contracts, and review rules for agent work.",
    templates: ["UNITY-ARCHITECTURE"],
    artifacts: [
      "Unity architecture doc",
      "Folder and namespace rules",
      "Scene and prefab ownership map",
      "Architecture review checklist",
    ],
  },
  {
    id: "module-05",
    number: 5,
    title: "Parallel Gameplay Production",
    status: "complete",
    timeBudget: "12-20 hours",
    phase: "Integrate",
    gate: "At least two independent gameplay slices are built in parallel and integrated without unreviewable merge chaos.",
    summary: "Run parallel agent work with branch/worktree ownership, slice briefs, review gates, and integration evidence.",
    templates: ["TASK-GRAPH"],
    artifacts: [
      "Task graph",
      "Branch/worktree plan",
      "Slice briefs and reviews",
      "Integration evidence log",
    ],
  },
  {
    id: "module-06",
    number: 6,
    title: "Hybrid Asset And Technical Art Pipeline",
    status: "complete",
    timeBudget: "10-18 hours",
    phase: "Integrate",
    gate: "A new asset can be generated or sourced, imported, validated, documented, and used in-game without breaking style, provenance, disclosure, or commercial-use clarity.",
    summary: "Create a production asset pipeline that handles style, technical import, proof, commercial use, and AI disclosure.",
    templates: ["STYLE-BIBLE", "ASSET-LEDGER"],
    artifacts: [
      "Style bible",
      "Asset ledger",
      "Proof files",
      "Asset acceptance note",
    ],
  },
  {
    id: "module-07",
    number: 7,
    title: "Editor Automation And Tooling",
    status: "complete",
    timeBudget: "8-14 hours",
    phase: "Verify",
    gate: "The project catches common Unity production mistakes before a human playtest.",
    summary: "Build small, reviewable editor tools and validators that reduce repeated production mistakes.",
    templates: [],
    artifacts: [
      "Automation boundary note",
      "Validator spec",
      "Validation evidence",
      "Tool runbook",
    ],
  },
  {
    id: "module-08",
    number: 8,
    title: "Verification For Games",
    status: "complete",
    timeBudget: "10-16 hours",
    phase: "Verify",
    gate: "A broken core mechanic, failed build, missing reference, or packaging failure is caught before the final release package.",
    summary: "Build a practical verification loop with tests, smoke path, build checks, performance budget, input checks, and bug intake.",
    templates: ["QA-PLAN"],
    artifacts: [
      "QA plan",
      "Edit/play mode evidence",
      "Build verification checklist",
      "Verification evidence note",
    ],
  },
  {
    id: "module-09",
    number: 9,
    title: "Polish, Feel, UX, And Player Clarity",
    status: "complete",
    timeBudget: "12-20 hours",
    phase: "Polish",
    gate: "A new player understands the goal, controls, feedback, and failure state without developer explanation.",
    summary: "Use playtest evidence to improve onboarding, feel, menus, accessibility basics, feedback, pacing, and capture staging.",
    templates: ["PLAYTEST-RUBRIC"],
    artifacts: [
      "Playtest rubric",
      "Player clarity evidence",
      "Accessibility basics note",
      "Screenshot and trailer candidates",
    ],
  },
  {
    id: "module-10",
    number: 10,
    title: "Steam-Demo Candidate Package And Maintenance",
    status: "complete",
    timeBudget: "8-14 hours",
    phase: "Package",
    gate: "The output is a Steam-demo candidate package. Actual Steamworks upload is an optional extension.",
    summary: "Package the verified slice with build evidence, release notes, store-copy prep, disclosure prep, and continuation handoff.",
    templates: ["STEAM-DEMO-CANDIDATE-CHECKLIST", "FRESH-AGENT-HANDOFF"],
    artifacts: [
      "Windows build path",
      "Steam-demo candidate checklist",
      "Demo README and known issues",
      "Fresh-agent handoff",
    ],
  },
];

export const templates = [
  "AGENT-ROLES",
  "ASSET-LEDGER",
  "CUT-PLAN",
  "FRESH-AGENT-HANDOFF",
  "GAME-THESIS",
  "PLAYTEST-RUBRIC",
  "QA-PLAN",
  "STEAM-DEMO-CANDIDATE-CHECKLIST",
  "STYLE-BIBLE",
  "TASK-GRAPH",
  "UNITY-ARCHITECTURE",
  "VERTICAL-SLICE-SPEC",
];

export function getModuleById(id) {
  return modules.find((module) => module.id === id) ?? modules[0];
}

export function getCadenceById(id) {
  return cohortCadences.find((cadence) => cadence.id === id) ?? cohortCadences[0];
}
