import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { modules, templates } from "../src/courseData.js";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(root);
const docsRoot = join(repoRoot, "docs", "course-3");
const outputPath = join(root, "src", "generatedCourseContent.js");

export async function generateContent() {
  const moduleContent = await readModules();
  const templateContent = await readTemplates();

  await writeFile(
    outputPath,
    [
      "// Generated by scripts/generateContent.mjs. Do not edit by hand.",
      `export const moduleContent = ${JSON.stringify(moduleContent, null, 2)};`,
      "",
      `export const templateContent = ${JSON.stringify(templateContent, null, 2)};`,
      "",
      `export const contentStats = ${JSON.stringify(
        {
          modules: Object.keys(moduleContent).length,
          templates: Object.keys(templateContent).length,
        },
        null,
        2,
      )};`,
      "",
    ].join("\n"),
  );

  return {
    modules: Object.keys(moduleContent).length,
    templates: Object.keys(templateContent).length,
    outputPath,
  };
}

async function readModules() {
  const modulesDir = join(docsRoot, "modules");
  const files = await readdir(modulesDir);
  const content = {};

  for (const module of modules) {
    const prefix = `MODULE-${String(module.number).padStart(2, "0")}-`;
    const filename = files.find((file) => file.startsWith(prefix) && file.endsWith(".md"));
    if (!filename) {
      throw new Error(`Missing module doc for ${module.id}`);
    }

    const filePath = join(modulesDir, filename);
    const parsed = await parseMarkdownFile(filePath);
    if (parsed.sections.length < 5) {
      throw new Error(`Module doc ${filename} has too few sections to render`);
    }

    content[module.id] = {
      id: module.id,
      title: parsed.title,
      sourcePath: displayPath(filePath),
      sections: parsed.sections,
    };
  }

  return content;
}

async function readTemplates() {
  const templatesDir = join(docsRoot, "templates");
  const content = {};

  for (const template of templates) {
    const filePath = join(templatesDir, `${template}.md`);
    const parsed = await parseMarkdownFile(filePath);
    if (parsed.sections.length < 3) {
      throw new Error(`Template doc ${template}.md has too few sections to render`);
    }

    content[template] = {
      id: template,
      title: parsed.title,
      sourcePath: displayPath(filePath),
      sections: parsed.sections,
    };
  }

  return content;
}

async function parseMarkdownFile(filePath) {
  const markdown = await readFile(filePath, "utf8");
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  let title = "";
  let current = null;
  const sections = [];

  for (const line of lines) {
    const h1 = line.match(/^#\s+(.+)$/);
    if (h1 && !title) {
      title = h1[1].trim();
      continue;
    }

    const h2 = line.match(/^##\s+(.+)$/);
    if (h2) {
      pushSection(sections, current);
      current = { title: h2[1].trim(), body: [] };
      continue;
    }

    if (current) {
      current.body.push(line);
    }
  }

  pushSection(sections, current);

  if (!title) {
    throw new Error(`Missing title in ${filePath}`);
  }
  if (sections.length === 0) {
    throw new Error(`Missing sections in ${filePath}`);
  }

  return { title, sections };
}

function pushSection(sections, section) {
  if (!section) {
    return;
  }

  const body = section.body.join("\n").trim();
  if (!body) {
    return;
  }

  sections.push({
    title: section.title,
    body,
  });
}

function displayPath(filePath) {
  return relative(repoRoot, filePath).split(sep).join("/");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const result = await generateContent();
  console.log(
    `Generated Course 3 content: ${result.modules} modules, ${result.templates} templates -> ${displayPath(result.outputPath)}`,
  );
}
