import type { WeekData } from "../types.ts";

export const WEEK_10: WeekData = {
  meta: {
    id: "10",
    title: "Talking about the whole system, not just one file",
    capability: "STEER",
    picture: "a restaurant building with a dining room, kitchen, pantry, and outside suppliers",
    status: "built",
  },
  lessons: [
    {
      id: "w10-l1",
      number: "01",
      title: "The Whole Building",
      summary: "Inspect every layer, then trace one order from the screen to an outside service and back.",
      widgetId: "week10-building",
      code: {
        title: "One action crosses the system and returns",
        lang: "TypeScript",
        lines: [
          { code: "const reply = await fetch('/api/orders', {", note: "the screen sends the customer's order to the logic layer" },
          { code: "  method: 'POST', body: JSON.stringify(order)", note: "the request carries the order across the layer boundary" },
          { code: "});", note: "the API checks the rules and coordinates the hidden work" },
          { code: "const savedOrder = await reply.json();", note: "data from the completed round trip comes back" },
          { code: "showConfirmation(savedOrder);", note: "the screen draws the answer for the customer" },
        ],
      },
    },
    {
      id: "w10-l2",
      number: "02",
      title: "Rearrange the Kitchen",
      summary: "Sort each responsibility into its layer and see why clear ownership makes changes safer.",
      widgetId: "week10-layers",
      code: {
        title: "Give each layer one kind of job",
        lang: "TypeScript",
        lines: [
          { code: "screen.onSubmit(orderForm);", note: "the screen gathers the user's action" },
          { code: "const total = logic.price(orderForm);", note: "logic applies the business rule" },
          { code: "const order = await data.save(orderForm);", note: "the data layer owns reading and saving" },
          { code: "await payments.charge(order.id, total);", note: "an adapter talks to the outside payment service" },
          { code: "screen.showReceipt(order);", note: "the answer returns to the visible layer" },
        ],
      },
    },
  ],
  cards: [
    { lessonId: "w10-l1", q: "A customer presses Pay. Which layer should receive that action first?", a: "The screen layer. It notices the click and asks the logic/API layer to handle the order." },
    { lessonId: "w10-l1", q: "The payment provider approves a charge. Does the answer jump straight onto the screen?", a: "No. It returns through the app's logic, which saves or shapes the result before the screen displays it." },
    { lessonId: "w10-l1", q: "What does an architecture view help you steer?", a: "It helps you direct where responsibilities and connections belong across the whole system, not just how one line is written." },
    { lessonId: "w10-l2", q: "Where should the rule 'orders over Rs 500 get free delivery' live?", a: "In the logic layer. It is a business decision, not a screen drawing or database storage job." },
    { lessonId: "w10-l2", q: "Why should a screen component avoid writing directly to the database?", a: "It mixes visible UI work with storage rules. That makes security, testing, and later changes harder to control." },
    { lessonId: "w10-l2", q: "What is separation of concerns in one sentence?", a: "Give each part one clear kind of job, with clear handoffs to the other parts." },
  ],
  resources: [
    {
      title: "Client-server overview",
      source: "MDN Web Docs",
      time: "20 min read",
      why: "Follows a browser request through server work and back as a response.",
      url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Client-Server_overview",
      group: "core",
    },
    {
      title: "Introduction to the server side",
      source: "MDN Web Docs",
      time: "15 min read",
      why: "Shows how visible page code, server code, and stored data divide the work.",
      url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/First_steps/Introduction",
      group: "core",
    },
    {
      title: "Common web application architectures",
      source: "Microsoft Learn",
      time: "25 min read",
      why: "An official guide to layers and separation of concerns in growing applications.",
      url: "https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures",
      group: "deeper",
    },
    {
      title: "Deployment archetypes",
      source: "Google Cloud Architecture Center",
      time: "15 min read",
      why: "Shows the real choices behind placing a built application where users can reach it.",
      url: "https://docs.cloud.google.com/architecture/deployment-archetypes",
      group: "deeper",
    },
  ],
  glossaryTerms: [
    {
      slug: "separation-of-concerns",
      term: "separation of concerns",
      weekId: "10",
      plain: "Giving each part of a system one clear kind of job. Parts cooperate through clear handoffs instead of all doing everything.",
      picture: "The waiter takes orders, the kitchen cooks, and the pantry stores ingredients. The waiter does not cook at the table.",
      code: "const total = pricing.calculate(order);\nawait orders.save(order);\nreceipt.show(total);",
      where: "Folders, modules, services, and review discussions about where a new responsibility belongs.",
    },
    {
      slug: "layer",
      term: "layer",
      weekId: "10",
      plain: "A group of code with one broad responsibility and a clear boundary around it.",
      picture: "One area of the restaurant building: dining room, kitchen, pantry, or supplier door.",
      code: "screen -> logic -> data -> outsideService",
      where: "Architecture diagrams and folders named UI, API, services, repositories, or adapters.",
    },
    {
      slug: "deploy",
      term: "deploy",
      weekId: "10",
      plain: "Putting a tested version of the app onto computers where its users can reach and run it.",
      picture: "Opening the finished restaurant building to customers after the rooms and equipment are ready.",
      code: "npm run build\ncloud deploy ./dist",
      where: "Release scripts, hosting dashboards, build pipelines, and messages about production.",
    },
    {
      slug: "architecture",
      term: "architecture",
      weekId: "10",
      plain: "The big-picture arrangement of a system's parts, responsibilities, and connections.",
      picture: "The building plan showing where the dining room, kitchen, pantry, and supplier entrance connect.",
      code: "screen -> api -> database\n              -> paymentService",
      where: "Planning before an AI changes several files, system diagrams, and decisions about where new work belongs.",
    },
  ],
};
