import type { WeekData } from "../types.ts";

export const WEEK_09: WeekData = {
  meta: {
    id: "09",
    title: "When the kitchen has many cooks",
    capability: "READ + SMELL + DEBUG",
    picture: "a coffee shop with drink buzzers and two people reaching for the last croissant",
    status: "built",
  },
  lessons: [
    {
      id: "w9-l1",
      number: "01",
      title: "The Coffee Shop",
      summary: "Predict the completion order, then compare one-at-a-time work with drinks that brew together.",
      widgetId: "week09-coffee",
      code: {
        title: "Start work, then wait for the answer you need",
        lang: "TypeScript",
        lines: [
          { code: "const espresso = makeDrink('espresso');", note: "start brewing; this is the buzzer promise" },
          { code: "const tea = makeDrink('iced tea');", note: "start another drink while espresso brews" },
          { code: "const firstReady = await tea;", note: "wait here until this drink is ready" },
          { code: "serve(firstReady);", note: "serve the completed drink" },
        ],
      },
    },
    {
      id: "w9-l2",
      number: "02",
      title: "The Last Croissant",
      summary: "Break a shared stock check, then add a lock and prove a retry cannot take the last item twice.",
      widgetId: "week09-race",
      code: {
        title: "Keep the check and the change together",
        lang: "TypeScript",
        lines: [
          { code: "await croissantLock.runExclusive(async () => {", note: "one request enters this stock room at a time" },
          { code: "  if (stock === 0) return soldOut();", note: "check the latest shared count" },
          { code: "  if (processed.has(orderId)) return alreadyDone();", note: "a retry with this ticket changes nothing" },
          { code: "  stock -= 1; processed.add(orderId);", note: "reserve once, then remember the ticket" },
          { code: "});", note: "release the lock for the next request" },
        ],
      },
    },
  ],
  cards: [
    {
      lessonId: "w9-l1",
      q: "Three drinks start together: iced tea takes 1 beat, cappuccino 2, espresso 3. Which comes out first?",
      a: "Iced tea. Async work can finish in duration order, not the order the barista started it.",
    },
    {
      lessonId: "w9-l1",
      q: "Does `await` mean the whole coffee shop stops?",
      a: "No. It pauses this async path until its answer is ready. Other work can continue while the buzzer is out.",
    },
    {
      lessonId: "w9-l1",
      q: "What is a Promise holding before a drink is ready?",
      a: "A placeholder for the later result, like the buzzer you hold while the drink is being made.",
    },
    {
      lessonId: "w9-l2",
      q: "Two requests both read `stock === 1` before either subtracts. What can go wrong?",
      a: "Both may promise the same croissant. That race condition can sell two items when only one existed.",
    },
    {
      lessonId: "w9-l2",
      q: "Why is a lock useful around the stock check and subtraction?",
      a: "It lets one request finish the shared check-and-change step before the next request sees the count.",
    },
    {
      lessonId: "w9-l2",
      q: "A network retry sends the same order ticket again. What should an idempotent order handler do?",
      a: "Recognize the ticket was already handled and return the earlier result without subtracting stock or charging again.",
    },
  ],
  resources: [
    {
      title: "async function",
      source: "MDN Web Docs",
      time: "12 min read",
      why: "The reference for async functions, promises, and where await may be used.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function",
      group: "core",
    },
    {
      title: "Promise",
      source: "MDN Web Docs",
      time: "15 min read",
      why: "Shows the states of unfinished work and the values that arrive later.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
      group: "core",
    },
    {
      title: "Idempotent glossary",
      source: "MDN Web Docs",
      time: "8 min read",
      why: "A compact HTTP reference for actions that can be repeated without changing the result again.",
      url: "https://developer.mozilla.org/en-US/docs/Glossary/Idempotent",
      group: "deeper",
    },
  ],
  glossaryTerms: [
    {
      slug: "synchronous",
      term: "synchronous",
      weekId: "09",
      plain: "Work that finishes one step before the next step starts.",
      picture: "Finish each coffee before beginning the next order.",
      code: "const drink = makeDrink('espresso');\nserve(drink);",
      where: "Simple calculations and code where each next line needs the finished value from the line above.",
    },
    {
      slug: "asynchronous",
      term: "asynchronous",
      weekId: "09",
      plain: "Work that starts now and finishes later, while other work can continue.",
      picture: "Start an espresso, then serve other customers while it brews.",
      code: "const drink = makeDrink('espresso');\nconst tea = makeDrink('iced tea');",
      where: "Network requests, timers, file reading, and other work that must wait on something outside the current line.",
    },
    {
      slug: "await",
      term: "await",
      weekId: "09",
      plain: "A word that pauses this async path until unfinished work gives back its result.",
      picture: "Wait at the counter until this drink's buzzer goes off.",
      code: "const order = await fetch('/api/order');",
      where: "Before fetch results, parsed response bodies, and other promises whose completed value the next line needs.",
    },
    {
      slug: "promise",
      term: "promise",
      weekId: "09",
      plain: "An object representing a result that is not ready yet but will arrive later or fail.",
      picture: "The buzzer handed over while a drink is still being made.",
      code: "const orderPromise = fetch('/api/order');",
      where: "The value returned by async functions, fetch calls, timers, and many browser APIs.",
    },
    {
      slug: "race-condition",
      term: "race condition",
      weekId: "09",
      plain: "A bug where the result depends on which competing piece of work reaches shared state first.",
      picture: "Two customers both reach for the last croissant before the display is updated.",
      code: "if (stock > 0) stock -= 1;",
      where: "Shared counters, stock, payments, saves, and UI updates started by more than one request.",
    },
    {
      slug: "idempotency",
      term: "idempotency",
      weekId: "09",
      plain: "Making the same request again has the same effect as making it once.",
      picture: "Pressing the lift button twice does not send two lifts.",
      code: "if (processed.has(orderId)) return previousResult;",
      where: "Payment, order, and save endpoints that may be retried after a slow or lost network reply.",
    },
  ],
};
