import type { WeekData } from "../types.ts";

export const WEEK_08: WeekData = {
  meta: {
    id: "08",
    title: "Checking the AI's work before you say yes",
    capability: "SMELL + STEER",
    picture: "suggested edits that you accept or reject one at a time",
    status: "built",
  },
  lessons: [
    {
      id: "w8-l1",
      number: "01",
      title: "Approve or Reject",
      summary: "Read the changed lines, choose a verdict, and name the risk before accepting.",
      widgetId: "approve-reject",
      code: {
        title: "The line that waits for real data",
        lang: "TypeScript",
        lines: [
          { code: "const response = await fetch('/api/orders');", note: "wait for the reply" },
          { code: "if (!response.ok) throw new Error('Load failed');", note: "stop on a bad reply" },
          { code: "const orders = await response.json();", note: "wait while JSON is read" },
          { code: "setOrders(orders);", note: "keep the real list on screen" },
        ],
      },
    },
    {
      id: "w8-l2",
      number: "02",
      title: "Build the Bug Report",
      summary: "Keep the evidence another person needs and leave out the noise.",
      widgetId: "bug-report-builder",
      code: {
        title: "A bug report as structured evidence",
        lang: "TypeScript",
        lines: [
          { code: "const bugReport = {", note: "one evidence bundle" },
          { code: "  changed: 'Added Save validation',", note: "what changed" },
          { code: "  expected: 'Valid form saves',", note: "what should happen" },
          { code: "  actual: 'TypeError: response.json is not a function',", note: "what happened instead" },
          { code: "};", note: "ready to hand back" },
        ],
      },
    },
  ],
  cards: [
    {
      lessonId: "w8-l1",
      q: "A diff adds `import helper from 'instant-perfect-ai'`, but package.json never lists it. Approve or reject?",
      a: "Reject it. The package may be made up, unsafe, or simply missing. Verify it before installing or accepting the import.",
    },
    {
      lessonId: "w8-l1",
      q: "A refactor removes the only `setOrders(orders)` line. The page still builds. Is the diff safe?",
      a: "No. A clean build does not prove the behavior survived. The page can load while never putting the fetched orders on screen.",
    },
    {
      lessonId: "w8-l1",
      q: "Why review the changed lines before reading the whole file?",
      a: "The diff is the small list of proposed edits. It tells you where behavior may have changed, so you can inspect the risky places first.",
    },
    {
      lessonId: "w8-l1",
      q: "A diff removes `await` before `response.json()`. Why can that break the next line?",
      a: "Without await, the variable holds unfinished work called a Promise instead of the parsed data the next line expects.",
    },
    {
      lessonId: "w8-l1",
      q: "When is plan mode useful?",
      a: "Use it before a change when you want to inspect the intended files, steps, and boundaries before the agent edits anything.",
    },
    {
      lessonId: "w8-l1",
      q: "Why keep rules in CLAUDE.md or AGENTS.md instead of repeating them in every prompt?",
      a: "The project rules stay beside the code, so each agent can read the same boundaries before starting work.",
    },
    {
      lessonId: "w8-l2",
      q: "Which is more useful: `it is broken` or the exact red error text?",
      a: "The exact error text. It gives the next person a searchable clue and names the failing code shape.",
    },
    {
      lessonId: "w8-l2",
      q: "A bug report says what changed and what happened. What important part is still missing?",
      a: "What you expected to happen. Without that, the reviewer cannot tell the intended behavior from the bug.",
    },
    {
      lessonId: "w8-l2",
      q: "Should a bug report include every unrelated console message?",
      a: "No. Include the exact relevant error and the shortest useful context. Extra noise can hide the clue.",
    },
  ],
  resources: [
    {
      title: "Reviewing proposed changes in a pull request",
      source: "GitHub Docs",
      time: "15 min read",
      why: "The real review surface for inspecting changed files and leaving a verdict.",
      url: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request",
      group: "core",
    },
    {
      title: "About pull request reviews",
      source: "GitHub Docs",
      time: "10 min read",
      why: "Explains approve, request changes, and comment as real review outcomes.",
      url: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews",
      group: "core",
    },
    {
      title: "async function",
      source: "MDN Web Docs",
      time: "12 min read",
      why: "A reference for the missing-await failure you learn to smell in a diff.",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function",
      group: "core",
    },
    {
      title: "About packages and modules",
      source: "npm Docs",
      time: "10 min read",
      why: "Useful when a suggested import names a package you need to verify before trusting.",
      url: "https://docs.npmjs.com/about-packages-and-modules",
      group: "deeper",
    },
  ],
  glossaryTerms: [
    {
      slug: "plan-mode",
      term: "plan mode",
      weekId: "08",
      plain: "A pause where the AI shows intended edits before changing files.",
      picture: "Suggested edits laid on the desk for approval before anyone touches the document.",
      code: "// Plan: inspect -> list edits -> wait for approval",
      where: "AI coding tools when you ask for a plan or review before implementation.",
    },
    {
      slug: "diff-review",
      term: "diff review",
      weekId: "08",
      plain: "Reading the lines added and removed, then deciding whether the change is safe.",
      picture: "Track Changes in a shared document, with each edit visible before acceptance.",
      code: "- const data = response.json();\n+ const data = await response.json();",
      where: "Git changes, pull requests, and AI edit previews.",
    },
    {
      slug: "failure-mode",
      term: "failure mode",
      weekId: "08",
      plain: "A repeatable way a change can go wrong, even when it looks convincing.",
      picture: "A checklist of known weak spots you inspect before accepting delivery.",
      code: "import helper from 'made-up-package';",
      where: "Reviews where you check for fake imports, lost state, missing waits, and rule breaks.",
    },
    {
      slug: "claude-md",
      term: "CLAUDE.md",
      weekId: "08",
      plain: "A project file that tells Claude the standing rules for work in that folder.",
      picture: "House rules pinned where every helper sees them before starting.",
      code: "# CLAUDE.md\n- Run the build before finishing",
      where: "Projects that use Claude Code for agent-driven development.",
    },
    {
      slug: "agents-md",
      term: "AGENTS.md",
      weekId: "08",
      plain: "A project file that gives coding agents local instructions and boundaries.",
      picture: "House rules pinned where every helper sees them before starting.",
      code: "# AGENTS.md\n- Keep lessons framework-free",
      where: "Repositories where one or more coding agents collaborate.",
    },
    {
      slug: "bug-report",
      term: "bug report",
      weekId: "08",
      plain: "A small evidence bundle: what changed, what should happen, and what happened instead.",
      picture: "A clear note attached to the broken item so the next person can reproduce the problem.",
      code: "{ changed, expected, actual: exactErrorText }",
      where: "Issues, support requests, and a corrective prompt sent back to an AI.",
    },
  ],
};
